version: '3.7'

services:
  angular:
    hostname: localhost
    container_name: docker-angular-todo-container
    build:
      context: .
      args:
        configuration: production
    ports:
      - 80:80
